{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- if .Values.auth.username }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}

